name: Secret Example

on: [push]

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"

      - name: Pass Unique Identifier as an Environment Variable
        run: 'echo "$MY_SECRET" > key'
        shell: bash
        env:
            SSH_KEY: ${{secrets.MY_SECRET}}