name: Generate Unique Identifier and Pass to Python Script

on: 
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
    
    paths:
      - 'COMPLETED'  # This specifies that the workflow will only run when the COMPLETED file is committed

  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  generate-and-use-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Unique Identifier
        id: generate_id  # Corrected step ID
        run: |
          # Generate a unique identifier based on the repository and organization names
          UNIQUE_ID=$(echo "${{ github.repository_owner }}-${{ github.repository }}" | sha256sum | cut -d' ' -f1)
          echo "Unique Identifier: $UNIQUE_ID"
          
          # Save the unique ID to the GITHUB_OUTPUT environment file for use in later steps
          echo "unique_id=$UNIQUE_ID" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pass Unique Identifier as an Environment Variable
        run: |
          python run-on-completed.py
        env:
          UNIQUE_ID: ${{ steps.generate_id.outputs.unique_id }}  # Corrected reference to the output

      - name: Pass Unique Identifier as a Command-Line Argument
        run: |
          python run-on-completed.py --unique-id ${{ steps.generate_id.outputs.unique_id }}  # Corrected reference to the output
